### ISSUE TITLE
Sticky session (for socket.io)

### ISSUE THREAD

**Issue by IngwiePhoenix** [valiton/node-various-cluster#2]
Hey.

I just ran into an issue that actually was known and I just didn't realize it... Socket.IO uses multiple requests to do a handshake request. So I am having troubble with it. The solution is to map workers to IP's - or, clients in that regard. An example is:

https://github.com/indutny/sticky-session/blob/master/lib/sticky-session.js

Do you think this could be incorperated into various-cluster? I really wouldn't want to drop 2 cluster managers into one file just because of this little issue.

Kind regards, Ingwie

**Comment by hereandnow** [comment]
you can do it by yourself, this doesnt need to be incorporated into various-cluster!

just iterate in your master over cluster.workers, and send them your sticky-session. to be save, you could send. various-cluster is just a wrapper around the cluster-module!

**Comment by IngwiePhoenix** [comment]
I tried to, but I got a variety of errors. Otherwise I wouldn’t ask :)

Placing the sticky() call below vaciousCluster.init() results in a worker trying to access process.env.WORKER_CONFIG, which is undefined. - although the worker I am trying to spawn doesn’t even use it.

SyntaxError: Unexpected token u
    at Object.parse (native)
    at new Worker (/Users/Ingwie/Work/BIRD3/node_modules/various-cluster/lib/worker.js:97:24)
    at VariousCluster.init (/Users/Ingwie/Work/BIRD3/node_modules/various-cluster/lib/various-cluster.js:123:7)
    at startWorkers (/Users/Ingwie/Work/BIRD3/new_app.js:52:8)
    at /Users/Ingwie/Work/BIRD3/new_app.js:100:9
    at _getports (/Users/Ingwie/Work/BIRD3/node_modules/getports/getports.js:20:14)
    at Socket.<anonymous> (/Users/Ingwie/Work/BIRD3/node_modules/getports/node_modules/getport/index.js:21:5)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
sticky-session: worker died

What is happening is, that various-cluster recognizes itself as child and tries to access an environment variable that doesnt exist.

I would recommend to add a check to see if this worker was indeed spawned by vc or not.

**Comment by hereandnow** [comment]
i don't get what you are trying to achieve?! using various-cluster inside a worker just isnt possible. you need to start it from a master-process ([see this example](https://github.com/valiton/node-various-cluster/blob/master/examples/variouscluster.js)! 

push your code which isnt working into a branch of your project, and i will take a look into it

**Comment by IngwiePhoenix** [comment]
Here’s a link to the entrence file. You can navigate to the root to see node-lib/frontent_worker.js 

http://git.ingwie.me/ingwie/bird3/blob/cluster-vc+sticky/new_app.js#L48 http://git.ingwie.me/ingwie/bird3/blob/cluster-vc+sticky/new_app.js#L48

**Comment by hereandnow** [comment]
what you are doing is calling the "startWorkers()" function from the master + every worker! that will definitily fail! you can only start workers from your master-process.

you probably shouldn't do anything else besides configuring your app, and starting the various-cluster in your master process!

this is probably how you would spawn your processes: 

https://gist.github.com/hereandnow/a0c2d0d905a67ff25ed9

creating the sticky session should reside in your frontend-worker!

**Comment by IngwiePhoenix** [comment]
Hey. I just had a good look at your updated version of my code.

The problem is, that `cluster.isMaster` is **false**. That hinders stuff like `sticky()` to actually work, since it thinks it already is a child, instead of actually being a master.

Have you thought about using `child_process.fork`? You could add this as an aditonal option.

``` javascript
{
    title: "foo process",
    count: N,
    asMaster: true
}
```

That, instead of using `cluster.fork()` would use `child_process.fork()`. You think this would be do-able? If so, I'd be ready to actually sit down and implement it - but i'd like to have your view on this beforehand :)

**Comment by IngwiePhoenix** [comment]
I put together a working example for using `child_process.fork`. And honestly, it looks pretty good!

``` javascript
var fork = require("child_process").fork;
var argv = require("optimist").argv;
var http = require("http");
var server = http.createServer();

if(!("is-child" in argv)) {
    // Master
    console.log(process.pid+": Forking self...");
    // Fork some
    var children=[];
    var current=0;
    for(i=0; i<2; i++) {
        console.log("... "+i);
        children[i] = fork(__filename, ["--is-child="+i]);
    }
    function run(sock) {
        console.log("current",current);
        if(current>=1) {
            current=0;
        } else {
            current++;
        }
        children[current].send("http", sock);
    }
    // Socket sharing does not work in raw child_process.fork!
    server.listen(9999, function(){
        console.log("Listening");
    });
    server.on("connection", function(sock){
        console.log("Master got socket");
        run(sock);
    });
} else {
    // Child
    process.on("message", function(msg, hd){
        console.log(argv["is-child"]+" Got connection...");
        server.emit("connection", hd);
    });
    server.on("request", function(req,res){
        res.end("Hello from "+argv["is-child"]);
    });
}
```

So if various-cluster would allow one to create workers through this method instead, it would be to them to distribute their sockets, if they wanted. Thus, they could use additonal cluster modules - such as sticky-sessions - without running into any issue. :)

So if you wouldn't mind, I can implement something for various-cluster! And, after doing research, various-cluster would be the _only_ module supporting this in a proper way.

**Comment by hereandnow** [comment]
this is NOT how various-cluster is supposed to work. you are spawning a server in the master + in each worker. why? the master is supposed to only handle alle workers and different worker types!

if you need more then 1 http-worker, why don't you just create the desired number of http-workers by various-cluster? you could share your socket through [msg](https://www.npmjs.com/package/msghub) which was build for interprocess communication through various-cluster. what i would do is this:

https://gist.github.com/hereandnow/ffa5ed7b73f484d4ce08

what i will not do is implement what you did. if you want that, fork various-cluster, and use the fork in your project (you can use modules from github)
